[project]
name = "zani"
description = "Zstandard-based Average Nucleotide Identity (ANI)"
authors = [{ name = "Tom Stanton", email = "tomdstanton@gmail.com" }]
readme = "README.md"
license = {file = "LICENSE"}
dynamic = ["version"]
keywords = ["bioinformatics", "ani", "pathogens", "genomics", "rust"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://tomdstanton.github.io/zani/"
Repository = "https://github.com/tomdstanton/zani"
Documentation = "https://tomdstanton.github.io/zani/"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
manifest-path = "crates/zani-py/Cargo.toml" 
module-name = "zani._zani_rs"