[project]
site_name = "zani"
repo_url = "https://github.com/tomdstanton/zani"
site_url = "https://tomdstanton.github.io/zani"
site_description = "A zero-dependency, ultra-fast Average Nucleotide Identity (ANI) estimator using Zstandard compression distance."
site_author = "Tom Stanton"
edit_uri = "edit/main/docs/"
repo_name = "tomdstanton/zani"
copyright = 'Maintained by <a href="https://tomdstanton.com">tomdstanton</a>.'

nav = [
    { "Home" = "index.md" },
    { "Modules" = "modules.md" },
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src/zani"]

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.action.edit",
    "content.action.view",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]


[project.theme.icon]
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"
repo = "fontawesome/brands/github"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "white"
accent = "deep orange"
toggle.icon =  "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "deep orange"
toggle.icon =  "material/brightness-4"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/tomdstanton/zani"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/zani"

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.toc]
permalink = true
