[package]
name = "zani" # The crates.io name
version.workspace = true
edition = "2024"
description = "Zstandard-based Average Nucleotide Identity (ANI)"
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
rayon = "1.8"
needletail = "0.5"
zstd = "0.13"
zstd-sys = { version = "2.0", features = ["experimental"] }
mimalloc = "0.1"
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"
bincode = "1.3"
anyhow = "1.0.102"
ryu = "1.0.23"
itoa = "1.0.18"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "engine_bench"
harness = false
