name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Install Python and Sync Dependencies
      run: uv sync
        
    - name: Run Cargo Clippy
      run: cargo clippy --workspace -- -D warnings
      
    - name: Run Cargo Integration Tests
      run: cargo test --release --workspace
      
    - name: Run Python Pytest Suite
      run: uv run pytest tests/
